version: "3"

services:
  vcode-redis:
    image: "redis:5.0.8"
    restart: always
    command: redis-server --requirepass vcodeRedisPassword
    volumes:
      - ./data/redis:/data
    ports:
      - "6378:6379"

  vcode-mongodb:
    image: "mongo:4.2.5"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: vcodeMongoPassword
      MONGO_INITDB_DATABASE: vcode
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27016:27017"

  vcode-spider:
    image: registry.cn-hangzhou.aliyuncs.com/vcodeteam/vcode-spider
    restart: always
    environment:
      REDIS_PASSWORD: vcodeRedisPassword
    volumes:
      - ./log/vcode-spider:/log/vcode-spider
    ports:
      - "8010:80"
    depends_on:
      - vcode-redis

  vcode-judger:
    image: registry.cn-hangzhou.aliyuncs.com/vcodeteam/vcode-judger
    restart: always
    environment:
      REDIS_PASSWORD: vcodeRedisPassword
    volumes:
      - ./log/vcode-judger:/var/log
      - ./data/vcode-judger/cases:/var/cases
    depends_on:
      - vcode-redis

  vcode:
    image: registry.cn-hangzhou.aliyuncs.com/vcodeteam/vcode
    restart: always
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: vcodeMongoPassword
      REDIS_PASSWORD: vcodeRedisPassword
    volumes:
      - ./log/vcode:/var/log/vcode
    ports:
      - "8000:8000"
    depends_on:
      - vcode-redis
      - vcode-mongodb

  vcode-web:
    image: registry.cn-hangzhou.aliyuncs.com/vcodeteam/vcode-web
    restart: always
    volumes:
      - ./log/nginx:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - vcode
